### ISSUE TITLE
TextNow保号报错！

### ISSUE THREAD

**Issue by fanmli** [Arronlong/py_scripts#1]
你好作者TextNow保号如果是一个账号就没有问题，要是2个以上就会出现错误如图，账号如：aaa,bbb,ccc 密码如：111,222,333 就会报错。

[URL=https://i.loli.net/2020/07/07/jPAcbYHCELgGtps.png][IMG]https://i.loli.net/2020/07/07/jPAcbYHCELgGtps.png[/IMG][/URL]

**Comment by Arronlong** [comment]
已更新
