### ISSUE TITLE
昨天还正常，今天就报错了

### ISSUE THREAD

**Issue by Cuiyim** [Arronlong/py_scripts#15]
执行了一段时间后突然出现了报错
![image](https://user-images.githubusercontent.com/51844650/103392858-b920b380-4b5a-11eb-9e17-f341cc5c17a7.png)

**Comment by Arronlong** [comment]
我这里显示是正常的....看报错信息，提示是DOMAINS的参数设置错了，你应该是更新过这个配置吧...
