### ISSUE TITLE
TextNow保号失效了？

### ISSUE THREAD

**Issue by fanmli** [Arronlong/py_scripts#16]
这两天TextNow保号失效了，在Actions看脚本运行和查看运行结果都没有问题，可是登陆TextNow账号里面没有发送信息，在TextNow账号设置里查看登陆历史设备就根本没有登陆账号，我十几个账号都一样，以前一直没问题就这两天开始失效的，从作者去年创立这个项目我一直使用都没有问题，麻烦作者看看这个问题谢谢！

查看运行结果；
<a href="https://sm.ms/image/bHc1XmSi4zpxu6a" target="_blank"><img src="https://i.loli.net/2021/01/23/bHc1XmSi4zpxu6a.png" ></a>

TextNow账号登陆历史信息：
<a href="https://sm.ms/image/7vYUQd4eTmkZAs5" target="_blank"><img src="https://i.loli.net/2021/01/23/7vYUQd4eTmkZAs5.png" ></a>

**Comment by GV13057911485** [comment]
是的，我也遇到相同的问题。

**Comment by UItramanTiga** [comment]
是的，我也遇到相同的问题。

**Comment by Arronlong** [comment]
了解了，这两天处理一下

**Comment by 282206796** [comment]
> 了解了，这两天处理一下

感谢大佬！抱拳~~~

**Comment by deepinor** [comment]
> 
> 
> 这两天TextNow保号失效了，在Actions看脚本运行和查看运行结果都没有问题，可是登陆TextNow账号里面没有发送信息，在TextNow账号设置里查看登陆历史设备就根本没有登陆账号，我十几个账号都一样，以前一直没问题就这两天开始失效的，从作者去年创立这个项目我一直使用都没有问题，麻烦作者看看这个问题谢谢！
> 
> 查看运行结果；
> [![](https://camo.githubusercontent.com/f7ffa89c7b6d5c407a6538b8ae57e60075356360f5c6640ef82261e03a99c5dd/68747470733a2f2f692e6c6f6c692e6e65742f323032312f30312f32332f62486331586d5369347a70787536612e706e67)](https://sm.ms/image/bHc1XmSi4zpxu6a)
> 
> TextNow账号登陆历史信息：
> [![](https://camo.githubusercontent.com/2e9fb9d6828b9cd75c47071ec72312d4c471393da7d5a95a04aa0fde384a5ba7/68747470733a2f2f692e6c6f6c692e6e65742f323032312f30312f32332f3776595551643465546d6b5a4173352e706e67)](https://sm.ms/image/7vYUQd4eTmkZAs5)

上周四之后失效的吧？

**Comment by fanmli** [comment]
> > 这两天TextNow保号失效了，在Actions看脚本运行和查看运行结果都没有问题，可是登陆TextNow账号里面没有发送信息，在TextNow账号设置里查看登陆历史设备就根本没有登陆账号，我十几个账号都一样，以前一直没问题就这两天开始失效的，从作者去年创立这个项目我一直使用都没有问题，麻烦作者看看这个问题谢谢！
> > 查看运行结果；
> > [![](https://camo.githubusercontent.com/f7ffa89c7b6d5c407a6538b8ae57e60075356360f5c6640ef82261e03a99c5dd/68747470733a2f2f692e6c6f6c692e6e65742f323032312f30312f32332f62486331586d5369347a70787536612e706e67)](https://sm.ms/image/bHc1XmSi4zpxu6a)
> > TextNow账号登陆历史信息：
> > [![](https://camo.githubusercontent.com/2e9fb9d6828b9cd75c47071ec72312d4c471393da7d5a95a04aa0fde384a5ba7/68747470733a2f2f692e6c6f6c692e6e65742f323032312f30312f32332f3776595551643465546d6b5a4173352e706e67)](https://sm.ms/image/7vYUQd4eTmkZAs5)
> 
> 上周四之后失效的吧？
是上周四失效的。

**Comment by MakeWorldGreat** [comment]
Same question，it did not work from Jan.22th.

**Comment by chwl66** [comment]
现在只能手动发送了

**Comment by tzchz** [comment]
我也是，九天之前失效的，说是无法定位element

**Comment by tzchz** [comment]
您好，应该是hCaptcha导致登录失败的原因
刚才登录试了一下，要完成hCaptcha验证，应该是reCap换成了hCap的原因。
好像说hCap可以通过无障碍cookie绕过去

**Comment by kdsbls** [comment]
现在还没有好

**Comment by WangEdward** [comment]
请问是否可以直接用 cookie 代替登录作为解决方案呢，感觉是可行的 @Arronlong

**Comment by 282206796** [comment]
请问有没有解决的办法比如用cookie或者chrome的插件

**Comment by Arronlong** [comment]
已解决，请更新最新版
