### ISSUE TITLE
保号任务失败！

### ISSUE THREAD

**Issue by GV13057911485** [Arronlong/py_scripts#17]
之前测试过6个号码，成功发送消息，在textnow上也可以看到这几个号码在发送消息。
后来再测试的时候，看任务同样是完成的，但textnow上没有发送消息，目标号码也没有收到消息，我猜测是textnow服务器端故意发送了一个欺骗性的应答给脚本，让脚本以为自己成功完成了任务，因本不是很懂程序代码，所以仅是猜测，供作者参考。

**Comment by UItramanTiga** [comment]
是的，我也遇到相同的问题。

**Comment by 282206796** [comment]
我也是这样，提示发送成功但是没有收到任何消息

**Comment by Arronlong** [comment]
#16

**Comment by Arronlong** [comment]
已解决，请更新最新版
