### ISSUE TITLE
TextNow真的失效了

### ISSUE THREAD

**Issue by ZeroTimeX** [Arronlong/py_scripts#19]
登录加入了机器人验证，验证过不了，哭吧。。。。

**Comment by Arronlong** [comment]
说的对...正在研究怎么突破...

**Comment by ZeroTimeX** [comment]
> 说的对...正在研究怎么突破...

可以从本地计算机获取Cookie保存，然后作为github的参数
可以参考我的修改
https://github.com/ZeroTimeX/py_scripts/blob/master/scripts/getCookie.py

https://github.com/ZeroTimeX/py_scripts/blob/master/.github/workflows/actions-textnow.yml

https://github.com/ZeroTimeX/py_scripts/blob/master/scripts/_textnow.py

https://github.com/ZeroTimeX/py_scripts/blob/master/scripts/textnow/textnow_sms.py

**Comment by WangEdward** [comment]
> > 说的对...正在研究怎么突破...
> 
> 可以从本地计算机获取Cookie保存，然后作为github的参数
> 可以参考我的修改
> https://github.com/ZeroTimeX/py_scripts/blob/master/scripts/getCookie.py
> 
> https://github.com/ZeroTimeX/py_scripts/blob/master/.github/workflows/actions-textnow.yml
> 
> https://github.com/ZeroTimeX/py_scripts/blob/master/scripts/_textnow.py
> 
> https://github.com/ZeroTimeX/py_scripts/blob/master/scripts/textnow/textnow_sms.py

你可以建个 PR

**Comment by Arronlong** [comment]
已解决，请更新最新版，最新版的确是基于cookie实现的，不过是参考了textnow_autosend项目的思路
