### ISSUE TITLE
希望大佬适配华为云国际版

### ISSUE THREAD

**Issue by ZiXia1** [Arronlong/py_scripts#20]
RT，谢谢

**Comment by Arronlong** [comment]
增加了华为云的支持，详见：https://github.com/Arronlong/py_scripts/tree/master/scripts/cf2dns ，代码是从其他人的代码修改而来，我自己没有账号进行测试，所以并没有做测试

**Comment by ravizhan** [comment]
> 增加了华为云的支持，详见：https://github.com/Arronlong/py_scripts/tree/master/scripts/cf2dns ，代码是从其他人的代码修改而来，我自己没有账号进行测试，所以并没有做测试

作为代码的原作者，我来说几句。
刚看了一下国际版的api，应该是通用的，没账号来测试。需要的话，可能得拖到7月了(我要中考)
至于为什么不用SDK有几个原因：
+ 文档看不懂(应该是我太菜了) 
+ 我比较熟悉openapi
+ SDK我也试过，但是一直不成功(可能还是我太菜了...)

**Comment by Arronlong** [comment]
> > 增加了华为云的支持，详见：https://github.com/Arronlong/py_scripts/tree/master/scripts/cf2dns ，代码是从其他人的代码修改而来，我自己没有账号进行测试，所以并没有做测试
> 
> 作为代码的原作者，我来说几句。
> 刚看了一下国际版的api，应该是通用的，没账号来测试。需要的话，可能得拖到7月了(我要中考)
> 至于为什么不用SDK有几个原因：
> 
> * 文档看不懂(应该是我太菜了)
> * 我比较熟悉openapi
> * SDK我也试过，但是一直不成功(可能还是我太菜了...)

英雄出少年啊，厉害

**Comment by Arronlong** [comment]
昨天加上代码后，没注意看，脚本居然都启动不了了，现在已经修复了
