### ISSUE TITLE
作者大大，我这更新了cookie后，还是收不到信息。。请问该如何解决TAT

### ISSUE THREAD

**Issue by MakeWorldGreat** [Arronlong/py_scripts#27]
action里面显示跑成功了，但是始终收不到短信。运行情况如图
![屏幕截图 2021-03-14 085944](https://user-images.githubusercontent.com/70130240/111054475-e6b5a180-84a7-11eb-9834-c45d1fb54617.png)
请求援助QAQ  谢谢！

**Comment by tangoog** [comment]
我也一样！

**Comment by Arronlong** [comment]
你们的代码都太旧了，hostloc的脚本都更新过2次了~删掉原项目，重新fork，原因：参数上跟之前比会有调整
