### ISSUE TITLE
自动更新优质CF IP已无法正常运行

### ISSUE THREAD

**Issue by aaro-n** [Arronlong/py_scripts#33]
本项目和官方项目都出现问题，也在vps上部署过，都无法正常运行。怀疑是运行环境改变。

**Comment by RainThings** [comment]
我也有这个问题

**Comment by Arronlong** [comment]
从你们的报错日志中看，是获取cf的ip接口失败。有可能被加入了黑名单，导致无法获取~

我刚提交了新的代码，增加了一个可选参数，CFIP_API_HOST，你们可以对api套上cf然后再访问。

当然也可以换个key试试：iDetkOys
