### ISSUE TITLE
大神，华为云国际是不支持吗？报错

### ISSUE THREAD

**Issue by doraemonlkmy** [Arronlong/py_scripts#37]
"message":"Invalid request. Unprocessable Entity.(422)"

**Comment by Arronlong** [comment]
由于本人没有华为云账号，不好调试，能否给我一下你的appid和appsecret进行调试一下。等调试完毕。你可以重新生成appsecret。
https://github.com/Arronlong 我的主页有一个联系我，可以加v，然后发给我调试一下...

**Comment by Arronlong** [comment]
感谢付出，已经修复了
