### ISSUE TITLE
哇，大佬，你能帮帮我吗（Can you help help me)？

### ISSUE THREAD

**Issue by MakeWorldGreat** [Arronlong/py_scripts#4]
大佬，我在网上搜到了你这个作品，因为我也需要TN保号。
可我没接触过写代码QAQ，照着你的指引操作了后失败了（可能是安装requirements.txt模块这一步骤出问题？）。。
大佬，无耻的问一下有录屏版教程吗TAT
万分感激！。！
失败表现为在Action界面没有结果。。。0 result.
![微信图片_20200824194025](https://user-images.githubusercontent.com/70130240/91040951-b7d9fa00-e641-11ea-9811-a28f8b65331b.png)
![微信图片_20200824194120](https://user-images.githubusercontent.com/70130240/91040997-cde7ba80-e641-11ea-86b2-f1b323cca3b1.png)

**Comment by Arronlong** [comment]
你是不是Action第二步没有执行：
![](https://cdn.jsdelivr.net/gh/Arronlong/cdn/blogImg/20200825095123.png)

**Comment by MakeWorldGreat** [comment]
大佬，我第一步操作完后，返回secret修改一下账户信息，然后再返回Actions看，就显示为0 results...

**Comment by MakeWorldGreat** [comment]
我今天到处找身边有可能会编程的朋友，他们都没上过github....我枯了TAT

**Comment by Arronlong** [comment]
修改一下README文件，随便改点，然后提交一下，Actions里就有变化了

**Comment by MakeWorldGreat** [comment]
大佬，成功了。。。一点点!!!我按照你说的删除了readme里面的一个中文字，然后ACTION里面有东西！然后新的报错显示“进程以退出代码1完成”。大佬，请问这是我的Secretes相关值出问题了吗？。。。
![1](https://user-images.githubusercontent.com/70130240/91170582-ad843280-e70b-11ea-987a-b2dde314ac64.png)

**Comment by Arronlong** [comment]
对于“$ is not defined”的异常，我昨天提交了最新代码，已经向你发起pr请求了。
看了一下执行结果，正常了：https://github.com/MakeWorldGreat/py_scripts/runs/1034540440?check_suite_focus=true

你可以将pr合并到你的项目中就可以了
