### ISSUE TITLE
hostloc登录失败了

### ISSUE THREAD

**Issue by chwl66** [Arronlong/py_scripts#8]
![image](https://user-images.githubusercontent.com/58024471/100228517-c5af5c00-2f5d-11eb-9db0-087f503ce192.png)
好像是从昨天开始，登录失败了，换过以为是cookie失效了，换了还是不行！

**Comment by Arronlong** [comment]
前2天也提示我有失败，不过每天2次，这次失败了，下次还能成功，所以就没管它。
我刚看了一下，今天也是成功的

**Comment by Arronlong** [comment]
第三版已公布，使用selenium模拟用户真实操作来完成积分赚取，[查看最新说明](https://github.com/Arronlong/py_scripts/tree/master/scripts/hostloc)
